In [ ]:
# doing batch gradient descent

In [ ]:
import numpy as np

In [ ]:
from sklearn.datasets import load_diabetes

In [ ]:
X, y = load_diabetes(return_X_y= True)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 2)

In [ ]:
# first doing a normal linear regression on this

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X, y)

LinearRegression()

In [ ]:
lr.intercept_

np.float64(152.13348416289597)

In [ ]:
lr.coef_

array([ -10.0098663 , -239.81564367,  519.84592005,  324.3846455 ,
       -792.17563855,  476.73902101,  101.04326794,  177.06323767,
        751.27369956,   67.62669218])

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
y_pred

array([152.38094643, 199.28001608, 124.34152283, 106.90148495,
       254.06119047, 261.50385365, 116.58117777, 120.33362197,
        99.73771331, 190.33892524, 138.95823614, 172.85421282,
       178.70270016, 138.35467112, 291.23106133,  89.95923929,
       211.85894518, 155.22669143, 131.0856888 , 121.22668124,
       150.50028158, 166.55796947, 153.63277325, 170.44330954,
       132.17560518, 230.55961445, 197.04628448,  99.13924946,
        53.72959077, 231.29474031, 249.1510082 , 116.18319159,
        69.84285129,  93.67249793, 197.5039462 , 172.67625919,
       157.80220788, 191.90710484, 115.06915952, 235.18106509,
       140.41937377, 117.45232726, 191.33777472, 189.95771575,
       176.88279035, 147.71997564, 163.36806262, 279.31133207,
       100.8597527 , 164.54245461, 249.89755705, 142.51704894,
       156.57659557, 115.86820464, 189.19505093,  81.79874055,
       122.05921633,  72.73116856, 157.72539008, 165.48779206,
       163.01540596, 157.92364009,  99.59081773, 235.16

In [ ]:
# finding the r2 score
from sklearn.metrics import r2_score

In [ ]:
r2_score(y_test, y_pred)

0.45729681888868934

In [ ]:
# creating our own gradient descnet class

In [ ]:
X_train.shape

(353, 10)

In [ ]:
y_train.shape

(353,)

In [ ]:
# crating our own class

In [ ]:
class BGD:

  def __init__(self, learning_rate, epochs):
    self.learning_rate = learning_rate
    self.epochs = epochs
    self.intercept_ = None
    self.coeff_ = None

  def fit(self, X_train, y_train):
    self.intercept_ = 0
    self.coeff_ = np.ones(X_train.shape[1])
    for i in range(self.epochs):
      y_hat = np.dot(X_train, self.coeff_) + self.intercept_
      intercept_der = -2 * np.mean(y_train - y_hat)
      self.intercept_ = self.intercept_ - (self.learning_rate * intercept_der)

      coeff_der = -2* np.dot(X_train.T, (y_train - y_hat)) / X_train.shape[0]
      self.coeff_ = self.coeff_ - (self.learning_rate * coeff_der)

  def predict(self, X_test):
    return (np.dot(X_test, self.coeff_) + self.intercept_)


In [ ]:
bgdregressor = BGD(0.9, 1000)

In [ ]:
bgdregressor.fit(X_train, y_train)

In [ ]:
bgdregressor.intercept_

np.float64(151.94728242532852)

In [ ]:
bgdregressor.coeff_

array([  -2.10863024, -201.86026233,  526.51664164,  338.75936102,
        -57.55954437, -129.3689685 , -190.44695827,   89.07780072,
        505.75881315,   70.74683771])

In [ ]:
y_pred2 = bgdregressor.predict(X_test)

In [ ]:
r2_score(y_test, y_pred2)

0.4482167497950553