In [ ]:
import numpy as np
from sklearn.datasets import load_diabetes

In [ ]:
X,y = load_diabetes(return_X_y= True)

In [ ]:
X.shape

(442, 10)

In [ ]:
y.shape

(442,)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size= 0.2, random_state= 20)

In [ ]:
X_train

array([[-0.02004471, -0.04464164, -0.046085  , ..., -0.03949338,
        -0.05140387, -0.04664087],
       [ 0.05260606,  0.05068012, -0.02452876, ..., -0.00259226,
         0.02671684, -0.03835666],
       [ 0.06350368,  0.05068012,  0.08864151, ...,  0.07120998,
         0.02929656,  0.07348023],
       ...,
       [-0.09996055, -0.04464164, -0.02345095, ..., -0.03949338,
        -0.01811369, -0.05078298],
       [ 0.03807591,  0.05068012,  0.00888341, ..., -0.00259226,
        -0.01811369,  0.00720652],
       [-0.07453279,  0.05068012, -0.00943939, ..., -0.00259226,
        -0.03324559,  0.01134862]])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2 = r2_score(y_test, lr.predict(X_test))

In [ ]:
r2

0.4179775463198647

In [ ]:
lr.intercept_

np.float64(153.71781244192604)

In [ ]:
lr.coef_

array([  -40.43205555,  -255.59694398,   561.21152097,   346.66073697,
       -1034.954276  ,   726.21636605,   167.03961699,   127.47606432,
         830.26629341,    51.24013529])

In [ ]:
# Making our own class

In [ ]:
from typing_extensions import Self
class MLR:

  def __init__(self):
    self.coef_ = None
    self.intercept_ = None

  def fit(self, X_train, y_train):
    X_train = np.insert(X_train, 0, 1, axis= 1)
    # to calculate coefficients
    betas = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
    self.intercept_ = betas[0]
    self.coef_ = betas[1:]

  def predict(self, X_test):
    return self.intercept_ + np.dot(X_test, self.coef_)

In [ ]:
lr = MLR()

In [ ]:
lr.fit(X_train, y_train)

In [ ]:
y_pred = lr.predict(X_test)

In [ ]:
r2_score(y_test, y_pred)

0.4179775463198647

In [ ]:
lr.intercept_

np.float64(153.717812441926)

In [ ]:
lr.coef_

array([  -40.43205555,  -255.59694398,   561.21152097,   346.66073697,
       -1034.954276  ,   726.21636605,   167.03961699,   127.47606432,
         830.26629341,    51.24013529])