In [1]:
# Performing multiple ridge regression using gradient descent

In [2]:
import numpy as np

In [3]:
from sklearn.datasets import load_diabetes

In [4]:
X, y = load_diabetes(return_X_y= True)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 20)

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
lr = LinearRegression()

In [10]:
lr.fit(X_train, y_train)

LinearRegression()

In [11]:
lr.intercept_

np.float64(153.71781244192604)

In [15]:
lr.coef_

array([  -40.43205555,  -255.59694398,   561.21152097,   346.66073697,
       -1034.954276  ,   726.21636605,   167.03961699,   127.47606432,
         830.26629341,    51.24013529])

In [16]:
X_train.shape

(353, 10)

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2_score(y_test, lr.predict(X_test))

0.4179775463198647

In [19]:
from sklearn.linear_model import Ridge

In [29]:
rd = Ridge(0.1)

In [30]:
rd.fit(X_train, y_train)

Ridge(alpha=0.1)

In [31]:
rd.intercept_

np.float64(153.7070503976234)

In [32]:
rd.coef_

array([ -16.70681541, -212.63581298,  520.38254197,  318.8744534 ,
        -81.52763218,  -39.74905081, -196.89336351,   87.32757248,
        413.26125656,   75.12823366])

In [33]:
r2_score(y_test, rd.predict(X_test))

0.4351017665889252

In [34]:
# creating our own class using gradient descent

In [83]:
from operator import le
class RidgeGD:

  def __init__(self, alpha, learning_rate, epochs):
    self.alpha = alpha
    self.epochs = epochs
    self.learning_rate = learning_rate
    self.coef_ = None

  def fit(self, X_train, y_train):
    self.intercept_ = 0
    self.coef_ = np.ones(X_train.shape[1]+1).reshape(-1, 1)
    X_train = np.insert(X_train, 0, 1, axis= 1)
    for i in range(self.epochs):
      coeff_der = np.dot(X_train.T, X_train).dot(self.coef_) - np.dot(X_train.T, y_train.reshape(-1, 1)) + self.alpha * self.coef_
      self.coef_ = self.coef_ - (self.learning_rate * coeff_der)

  def predict(self, X_test):
    X_test = np.insert(X_test, 0, 1, axis= 1)
    return (np.dot(X_test, self.coef_.reshape(-1, 1)))

In [84]:
ridge = RidgeGD(0.1, 0.001, 100)

In [85]:
ridge.fit(X_train, y_train)

In [86]:
ridge.coef_

array([[154.35266594],
       [ 18.05043003],
       [  1.00991594],
       [ 71.73797152],
       [ 53.0987683 ],
       [ 22.46942548],
       [ 18.34212478],
       [-42.78569021],
       [ 46.0697149 ],
       [ 63.80828428],
       [ 41.11026253]])

In [87]:
r2_score(y_test, ridge.predict(X_test))

0.15305197784858504

In [44]:
# now using sgdregressor class

In [88]:
from sklearn.linear_model import  SGDRegressor

In [89]:
reg = SGDRegressor(penalty= 'l2', alpha= 0.001, max_iter= 500, eta0= 0.1, learning_rate= 'constant')

In [90]:
reg.fit(X_train, y_train)

SGDRegressor(alpha=0.001, eta0=0.1, learning_rate='constant', max_iter=500)

In [91]:
reg.intercept_

array([163.67459403])

In [92]:
reg.coef_

array([   7.95832962, -143.89482901,  420.90558036,  264.15875021,
        -12.27376748,  -48.09821551, -179.02213987,  112.23136143,
        313.96671121,  104.93223233])

In [93]:
r2_score(y_test, reg.predict(X_test))

0.3874034108836394