# we can do array operations like scalar and vector operation

In [24]:
import numpy as np

In [25]:
# Scalar operations
a = np.arange(10, 24).reshape(2, 7)
a

array([[10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23]])

In [26]:
# arithemtic operations
a + 2

array([[12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25]])

In [27]:
a - 2

array([[ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [28]:
a* 2

array([[20, 22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44, 46]])

In [29]:
a/2

array([[ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5]])

In [30]:
# Relational operations
a > 5

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [31]:
a >= 20

array([[False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True]])

In [32]:
# Vector operations, if both have same shape, then also operations will happen one by one
b = np.arange(20, 34).reshape(2, 7)
b

array([[20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33]])

In [33]:
a+b

array([[30, 32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54, 56]])

In [34]:
a-b

array([[-10, -10, -10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10, -10, -10]])

In [35]:
a > b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

Numpy provides so many functions, some of the main functions as follows

In [36]:
a = np.random.random((3, 3))
a = np.round(a * 100)
a

array([[93., 27.,  5.],
       [96., 33., 86.],
       [ 0., 62., 31.]])

In [37]:
#max
np.max(a)

96.0

In [38]:
#min
np.min(a)

0.0

In [39]:
#sum
np.sum(a)

433.0

In [40]:
#prod
np.prod(a)

0.0

In [41]:
# we can even get the above values from certain column or row or block or any other thing if we want as follows
# axis is an argument where 0 indicates highest dimension, and so axis 1 means we are travelling columns direction,operate rows wise and collapse rows
np.min(a, axis = 1)

array([ 5., 33.,  0.])

In [44]:
# if we do it for 3d matrix then we will get like this
a = np.round(np.random.random((3, 3, 3)) * 100)
a

array([[[69., 19., 79.],
        [ 1., 17., 66.],
        [63., 56., 23.]],

       [[22., 99., 87.],
        [46., 53.,  2.],
        [28., 61., 36.]],

       [[67., 77., 36.],
        [70., 79., 73.],
        [32., 61., 43.]]])

In [45]:
# now this has 3 dimensions and here axis = 0 operations by collapsing depth and thus gives us a single matrix of rows and columns,
#axis = 1, operates along rows so it collapses columns in each matrix and gives us seperate matrices which contains only rows
# axis = 2, operates along columns so it collapses only rows and gives us seperate matrices which contains the values of columns only
np.min(a, axis = 0)

array([[22., 19., 36.],
       [ 1., 17.,  2.],
       [28., 56., 23.]])

In [46]:
np.min(a, axis = 1)

array([[ 1., 17., 23.],
       [22., 53.,  2.],
       [32., 61., 36.]])

In [48]:
# axis =2,operate along columns meaning collapse rows
np.min(a, axis = 2) 

array([[19.,  1., 23.],
       [22.,  2., 28.],
       [36., 70., 32.]])

Statistical and mathematical functions, same if they are aggregate functions we can apply them across different axis

In [49]:
np.mean(a)

50.55555555555556

In [50]:
np.median(a)

56.0

In [51]:
np.std(a)

25.817498133563276

In [52]:
np.var(a)

666.5432098765433

In [53]:
np.sin(a)

array([[[-0.11478481,  0.14987721, -0.44411267],
        [ 0.84147098, -0.96139749, -0.02655115],
        [ 0.1673557 , -0.521551  , -0.8462204 ]],

       [[-0.00885131, -0.99920683, -0.82181784],
        [ 0.90178835,  0.39592515,  0.90929743],
        [ 0.27090579, -0.96611777, -0.99177885]],

       [[-0.85551998,  0.99952016, -0.99177885],
        [ 0.77389068, -0.44411267, -0.67677196],
        [ 0.55142668, -0.96611777, -0.83177474]]])

In [55]:
# dot product between two arrays is nothing but matrix multiplication of 2 matrices
a = np.arange(1, 13).reshape(3, 4)
b = np.arange(1, 13).reshape(4, 3)
np.dot(a, b)

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [56]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [57]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [58]:
np.round(a)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
np.ceil(a)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [60]:
np.floor(a)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])