# we can do array operations like scalar and vector operation

In [1]:
import numpy as np

In [2]:
# Scalar operations
a = np.arange(10, 24).reshape(2, 7)
a

array([[10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23]])

In [3]:
# arithemtic operations
a + 2

array([[12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25]])

In [4]:
a - 2

array([[ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [5]:
a* 2

array([[20, 22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44, 46]])

In [6]:
a/2

array([[ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ],
       [ 8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5]])

In [7]:
# Relational operations
a > 5

array([[ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [8]:
a >= 20

array([[False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True]])

In [9]:
# Vector operations, if both have same shape, then also operations will happen one by one
b = np.arange(20, 34).reshape(2, 7)
b

array([[20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33]])

In [10]:
a+b

array([[30, 32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54, 56]])

In [11]:
a-b

array([[-10, -10, -10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10, -10, -10]])

In [12]:
a > b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])