We can create a numpy array just by passing any sequence into array function

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [4]:
b = np.array((1, 2, 3, 4))
b

array([1, 2, 3, 4])

In [7]:
# Checking the type of array
type(a)

numpy.ndarray

In [8]:
# we can even create 2d and 3d arrays also
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#finidng the dimensions of the array
a.ndim

2

In [12]:
b = np.array([[[1,2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [13]:
b.ndim

3

In [15]:
# By default this took int32 as the data type
a.dtype

dtype('int32')

In [23]:
# we can even specify the type of datatype we want from the start itself
a = np.array([1, 2, 3, 4], dtype = 'int16')
a.dtype

dtype('int16')

In [24]:
# same as ranage function we can even create an array using arange function
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# we can even reshape the array we want
a = np.arange(1, 13)
a.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a.reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [28]:
# np.ones
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
# np.zeros
a = np.zeros((2, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# np.random
a = np.random.random((3, 4))
a

array([[0.62932919, 0.14289488, 0.59188459, 0.97944857],
       [0.46240864, 0.17568209, 0.50585654, 0.30091888],
       [0.86506919, 0.71666598, 0.48716625, 0.08225205]])

In [34]:
# np.linspace(this gives us an array of the elements we mentioned including first and last one with equal spaces
a = np.linspace(1, 10, 20)
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [36]:
# np.identity(gives identity matrix of the given dimensions
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
#a.shape 
a.shape

(3, 3)

In [38]:
# a.dtype
a.dtype

dtype('float64')

In [40]:
# gives the size of each elemnet
a.itemsize

8

In [43]:
# gives total no.of items in the array"
a.size

9

In [44]:
a.dtype

dtype('float64')

In [45]:
#we can change this to our desired data type
a.astype(np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)