In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 100, 15)
a

array([17, 85, 64, 33, 88, 47, 66, 56, 26, 17, 84, 29, 85, 91, 54])

In [3]:
# we can sort by directly using sort method 
np.sort(a)

array([17, 17, 26, 29, 33, 47, 54, 56, 64, 66, 84, 85, 85, 88, 91])

In [4]:
# for 2d array we have to specify which axis we want to sort
b = a.reshape(5, 3)
b

array([[17, 85, 64],
       [33, 88, 47],
       [66, 56, 26],
       [17, 84, 29],
       [85, 91, 54]])

In [8]:
# this sorts each row sepearetly
np.sort(b)

array([[17, 64, 85],
       [33, 47, 88],
       [26, 56, 66],
       [17, 29, 84],
       [54, 85, 91]])

In [9]:
np.sort(b, axis = 0)

array([[17, 29, 66],
       [17, 47, 84],
       [26, 56, 85],
       [33, 64, 88],
       [54, 85, 91]])

In [10]:
np.sort(b, axis = 1)

array([[17, 64, 85],
       [33, 47, 88],
       [26, 56, 66],
       [17, 29, 84],
       [54, 85, 91]])

In [12]:
# we can append eleemnts same like list
np.append(a, 100)

array([ 17,  64,  85,  33,  47,  88,  26,  56,  66,  17,  29,  84,  54,
        85,  91, 100])

In [17]:
# for 2d we have to specify which axis, either row or column
np.append(b, [[0, 1, 2]], axis = 0)

array([[17, 64, 85],
       [33, 47, 88],
       [26, 56, 66],
       [17, 29, 84],
       [54, 85, 91],
       [ 0,  1,  2]])

In [18]:
np.append(b, [[0], [1], [2], [3], [4]], axis = 1)

array([[17, 64, 85,  0],
       [33, 47, 88,  1],
       [26, 56, 66,  2],
       [17, 29, 84,  3],
       [54, 85, 91,  4]])

In [19]:
# we can concatenate two arrays same like hstack and vstack
a = np.random.randint(1, 100, 12).reshape(3, 4)
b = np.random.randint(1, 100, 12).reshape(3, 4)

In [20]:
a

array([[15, 99, 70, 57],
       [67, 84, 99, 23],
       [96,  4, 84,  6]])

In [21]:
b

array([[46, 11, 98, 66],
       [72, 82, 58, 53],
       [18,  8, 12, 80]])

In [22]:
np.concatenate((a, b))

array([[15, 99, 70, 57],
       [67, 84, 99, 23],
       [96,  4, 84,  6],
       [46, 11, 98, 66],
       [72, 82, 58, 53],
       [18,  8, 12, 80]])

In [23]:
# we can even provide axis for clarity
np.concatenate((a, b), axis = 1)

array([[15, 99, 70, 57, 46, 11, 98, 66],
       [67, 84, 99, 23, 72, 82, 58, 53],
       [96,  4, 84,  6, 18,  8, 12, 80]])

In [25]:
a = np.array([1, 1, 1, 1, 1, 2, 2, 2, 3, 4, 5])
np.unique(a)

array([1, 2, 3, 4, 5])

In [26]:
a.shape

(11,)

In [29]:
np.expand_dims(a,axis = 0).shape

(1, 11)

In [30]:
np.expand_dims(a, axis = 1).shape

(11, 1)

In [32]:
a = np.random.randint(1, 100, 15)
a

array([89, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 29])

In [34]:
# we can use np.where to find and replace based on condition np.where(condition, true, false), where gives the posiiton in arrray
np.where(a>10)

(array([ 0,  1,  3,  4,  5,  6,  7,  8, 11, 12, 13, 14], dtype=int64),)

In [35]:
np.where(a%2 ==0, 0, a)

array([89,  0,  0, 97,  0,  0, 25, 67,  0,  0,  0, 41, 67, 43, 29])

In [36]:
# np.argmax directly gives the index of the maximum valuye in a given array
np.argmax(a)

5

In [37]:
# if we use d matrix, we can mention axis to get the max 
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[69, 31, 82, 17],
       [22, 47,  3, 11],
       [30, 60, 35,  5],
       [ 5, 47, 34, 49],
       [53, 70, 48,  9],
       [13, 50, 48,  7]])

In [39]:
np.argmax(b, axis = 0)

array([0, 4, 0, 3], dtype=int64)

In [40]:
np.argmax(b, axis = 1)

array([2, 1, 1, 3, 1, 1], dtype=int64)

In [41]:
# similarly argmin
np.argmin(b, axis = 1)

array([3, 2, 3, 0, 3, 3], dtype=int64)

In [42]:
a

array([89, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 29])

In [43]:
# gives cummulative sum
np.cumsum(a)

array([ 89, 179, 183, 280, 316, 414, 439, 506, 556, 562, 572, 613, 680,
       723, 752])

In [44]:
# for 2d if no axis is mentioned converts into 1d array
b

array([[69, 31, 82, 17],
       [22, 47,  3, 11],
       [30, 60, 35,  5],
       [ 5, 47, 34, 49],
       [53, 70, 48,  9],
       [13, 50, 48,  7]])

In [45]:
np.cumsum(b)

array([ 69, 100, 182, 199, 221, 268, 271, 282, 312, 372, 407, 412, 417,
       464, 498, 547, 600, 670, 718, 727, 740, 790, 838, 845])

In [46]:
np.cumsum(b, axis = 0)

array([[ 69,  31,  82,  17],
       [ 91,  78,  85,  28],
       [121, 138, 120,  33],
       [126, 185, 154,  82],
       [179, 255, 202,  91],
       [192, 305, 250,  98]])

In [47]:
np.cumprod(a)

array([         89,        8010,       32040,     3107880,   111883680,
       -1920301248,  -762890944,   425914304,  -179121280, -1074727680,
        2137625088,  1743282688,   835823104,  1580655104, -1405642240])

In [48]:
a

array([89, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 29])

In [49]:
# we can even get percentile directly
np.percentile(a, 100)

98.0

In [50]:
np.percentile(a, 0)

4.0

In [51]:
# histograms(gives the count of elemeents in the given bin range)
np.histogram(a, [0, 10, 20, 30, 40, 50, 60, 70, 80 ,90, 100])

(array([2, 1, 2, 1, 2, 1, 2, 0, 1, 3], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [52]:
height = np.array([100, 120, 125, 130, 140, 100])
age = np.array([10, 11, 12, 13, 14, 15])
np.corrcoef(height, age)

array([[1.        , 0.21376683],
       [0.21376683, 1.        ]])

In [53]:
a

array([89, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 29])

In [54]:
items = [0, 10, 20, 30]
np.isin(a, items)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False])

In [55]:
np.isin(items, a)

array([False,  True, False, False])

In [57]:
a[np.isin(a,items)]

array([10])

In [58]:
a

array([89, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 29])

In [59]:
np.flip(a)

array([29, 43, 67, 41, 10,  6, 50, 67, 25, 98, 36, 97,  4, 90, 89])

In [60]:
b

array([[69, 31, 82, 17],
       [22, 47,  3, 11],
       [30, 60, 35,  5],
       [ 5, 47, 34, 49],
       [53, 70, 48,  9],
       [13, 50, 48,  7]])

In [61]:
np.flip(b)

array([[ 7, 48, 50, 13],
       [ 9, 48, 70, 53],
       [49, 34, 47,  5],
       [ 5, 35, 60, 30],
       [11,  3, 47, 22],
       [17, 82, 31, 69]])

In [62]:
a

array([89, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 29])

In [63]:
np.put(a, [0, -1], [10, 20])

In [64]:
a

array([10, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 20])

In [65]:
np.delete(a, [0, -1])

array([90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43])

In [66]:
a

array([10, 90,  4, 97, 36, 98, 25, 67, 50,  6, 10, 41, 67, 43, 20])

In [67]:
a = np.random.randint(1, 10, 5)

In [68]:
a

array([9, 3, 3, 8, 6])

In [69]:
b = np.random.randint(1, 10, 5)
b

array([7, 1, 6, 6, 9])

In [70]:
np.union1d(a, b)

array([1, 3, 6, 7, 8, 9])

In [71]:
np.intersect1d(a, b)

array([6, 9])

In [72]:
np.setdiff1d(a, b)

array([3, 8])

In [74]:
np.setxor1d(a, b)

array([1, 3, 7, 8])

In [75]:
a

array([9, 3, 3, 8, 6])

In [77]:
np.clip(a, a_min = 4, a_max = 5)

array([5, 4, 4, 5, 5])

In [79]:
np.clip(b, a_min = 4, a_max = 5)

array([5, 4, 5, 5, 5])