In [49]:
import numpy as np

In [50]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
a[2]

2

In [52]:
a[-4]

6

In [53]:
a[0:4]

array([0, 1, 2, 3])

In [54]:
a[-1:-3]

array([], dtype=int32)

In [55]:
# from above we can see that array slicing will always follow right hand side only
a[-3:-1]

array([7, 8])

In [56]:
a[9:2]

array([], dtype=int32)

In [57]:
# also from above we can see that it will not follow cyclically
a[0:-5]

array([0, 1, 2, 3, 4])

In [58]:
# for 2d arrays, first index always presents rows and 2nd one columns
a = np.round(np.random.random((3,4))*10)
a

array([[ 3., 10.,  3.,  7.],
       [ 0.,  3.,  1.,  2.],
       [ 9.,  2.,  3.,  7.]])

In [59]:
a[2, 3]

7.0

In [60]:
a[0:2, 1:-1]

array([[10.,  3.],
       [ 3.,  1.]])

In [61]:
a[0:, 1:]

array([[10.,  3.,  7.],
       [ 3.,  1.,  2.],
       [ 2.,  3.,  7.]])

In [62]:
a

array([[ 3., 10.,  3.,  7.],
       [ 0.,  3.,  1.,  2.],
       [ 9.,  2.,  3.,  7.]])

In [63]:
for i in a:
    print(i)

[ 3. 10.  3.  7.]
[0. 3. 1. 2.]
[9. 2. 3. 7.]


In [64]:
# we know for a 2d array, i takes 1 row as it's element each time, if we want to print each and every item seperately
for i in np.nditer(a):
    print(i)

3.0
10.0
3.0
7.0
0.0
3.0
1.0
2.0
9.0
2.0
3.0
7.0


In [65]:
a

array([[ 3., 10.,  3.,  7.],
       [ 0.,  3.,  1.,  2.],
       [ 9.,  2.,  3.,  7.]])

In [66]:
a.reshape(6,2)

array([[ 3., 10.],
       [ 3.,  7.],
       [ 0.,  3.],
       [ 1.,  2.],
       [ 9.,  2.],
       [ 3.,  7.]])

In [67]:
# transpose of a matrix
a.T

array([[ 3.,  0.,  9.],
       [10.,  3.,  2.],
       [ 3.,  1.,  3.],
       [ 7.,  2.,  7.]])

In [68]:
# ravel converts entire matrix into 1d arrray
a.ravel()

array([ 3., 10.,  3.,  7.,  0.,  3.,  1.,  2.,  9.,  2.,  3.,  7.])

In [69]:
# horizantal stack(must have same no of rows)
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
b = np.arange(10, 16).reshape(2,3)
b

array([[10, 11, 12],
       [13, 14, 15]])

In [71]:
np.hstack((a, b))

array([[ 0,  1,  2,  3,  4, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 13, 14, 15]])

In [72]:
# vertical stack(must have same no.of columns)
np.vstack((a.T, b.T))

array([[ 0,  5],
       [ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [10, 13],
       [11, 14],
       [12, 15]])

In [73]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
b

array([[10, 11, 12],
       [13, 14, 15]])

In [75]:
c = np.hstack((a, b))
c

array([[ 0,  1,  2,  3,  4, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 13, 14, 15]])

In [76]:
# we can even split the array we want
np.hsplit(c, 2)

[array([[0, 1, 2, 3],
        [5, 6, 7, 8]]),
 array([[ 4, 10, 11, 12],
        [ 9, 13, 14, 15]])]

In [77]:
# we can even split the way we want
a, b = np.hsplit(a, [2])
a

array([[0, 1],
       [5, 6]])

In [78]:
b

array([[2, 3, 4],
       [7, 8, 9]])

In [79]:
c

array([[ 0,  1,  2,  3,  4, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 13, 14, 15]])

In [80]:
a, b = np.hsplit(c, [2])
a

array([[0, 1],
       [5, 6]])

In [81]:
b

array([[ 2,  3,  4, 10, 11, 12],
       [ 7,  8,  9, 13, 14, 15]])

In [82]:
c

array([[ 0,  1,  2,  3,  4, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 13, 14, 15]])

In [83]:
a,b,d = np.hsplit(c, [2,4])
a

array([[0, 1],
       [5, 6]])

In [84]:
b

array([[2, 3],
       [7, 8]])

In [85]:
d

array([[ 4, 10, 11, 12],
       [ 9, 13, 14, 15]])

In [86]:
# We can even split vertically as we want
c

array([[ 0,  1,  2,  3,  4, 10, 11, 12],
       [ 5,  6,  7,  8,  9, 13, 14, 15]])

In [87]:
a = c.T
a

array([[ 0,  5],
       [ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [10, 13],
       [11, 14],
       [12, 15]])

In [88]:
np.vsplit(a, 2)

[array([[0, 5],
        [1, 6],
        [2, 7],
        [3, 8]]),
 array([[ 4,  9],
        [10, 13],
        [11, 14],
        [12, 15]])]

In [91]:
b,c = np.vsplit(a, [6])
b

array([[ 0,  5],
       [ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [10, 13]])

In [92]:
c

array([[11, 14],
       [12, 15]])

In [94]:
b, c, d = np.vsplit(a, [1, 5])
b

array([[0, 5]])

In [95]:
c

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [96]:
d

array([[10, 13],
       [11, 14],
       [12, 15]])