**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [46]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
# @title
#Code here
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [4]:
#Code here
a = int(input("Enter 1st number:"))
b = int(input("Enter 2nd number: "))
c = np.random.rand(a, b)
c

Enter 1st number:2
Enter 2nd number: 3


array([[0.20140429, 0.78623593, 0.49822114],
       [0.67806413, 0.59476334, 0.69134819]])

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [15]:
#Code here
a = int(input("Enter 1st number:"))
b = int(input("Enter 2nd number: "))
c = np.ones((a, b))
c[1:-1, 1:-1] = 0
c

Enter 1st number:4
Enter 2nd number: 4


array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

3###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [16]:
#Code here
a = np.random.rand(10)
a

array([0.30520922, 0.03439073, 0.52252378, 0.36685561, 0.81516131,
       0.80273685, 0.3751857 , 0.11171686, 0.94203945, 0.474479  ])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

NameError: name 'No' is not defined

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [25]:
#Code here
a = np.tile(np.arange(5), (5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [42]:
#code here
a = np.random.randint(low = 1, high = 100, size= (10, 2))
point = np.array([2,3])
distance = np.sqrt(np.sum(np.square(a-point),axis= 1)).astype(np.int32)
distance

array([ 93, 113, 104,  55, 105, 124,  77,  45,  85,  22], dtype=int32)

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here
(1, 5, 3)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [53]:
#Code here
a = input("Enter number seperated by spaces: ")
b = [int(x) for x in a.split(" ")]
float_array = np.array(b, dtype = np.float16)
print(np.flip(float_array))

Enter number seperated by spaces: 10 11
[11. 10.]


 ### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [54]:
#Code here
elements_count = np.array([1, 2, 3, 4]).size
elements_count

4

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [67]:
#Code here
def softmax_func(arr):
  if not (isinstance(arr, np.ndarray)):
    raise TypeError ("All inputs must be numpy arrays")
  return np.exp(arr) / np.sum(np.exp(arr))

a = np.array([1, 2, 3,4])
softmax_func(a)

array([0.0320586 , 0.08714432, 0.23688282, 0.64391426])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [71]:
#Coder here
def stack(*arr):
  if not all(isinstance(a, np.ndarray) for a in arr):
    raise TypeError("All inputs must be numpy arrays")
  return np.vstack(arr)

a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
stack(a, b)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [48]:
#Code here
from datetime import datetime, timedelta
def dates_bw(start, end):
  if not (isinstance(start, str) and isinstance(end, str)):
    raise TypeError("Inputs should be strings only")
  start_date = datetime.strptime(start, '%Y-%m-%d').date()
  end_date = datetime.strptime(end, '%Y-%m-%d').date()
  return np.array([(start_date + timedelta(days = i)).strftime('%Y-%m-%d') for i in range((end_date - start_date).days + 1)])

print(dates_bw('2025-12-26', '2025-12-31'))

['2025-12-26' '2025-12-27' '2025-12-28' '2025-12-29' '2025-12-30'
 '2025-12-31']


###`Q-14:` Subtract the mean of each row from a matrix.

In [74]:
#code here
a = np.random.randint(low= 1, high = 10, size=(3, 3))
print(a)
b = a - np.mean(a, axis = 1)
b

[[1 8 2]
 [9 2 6]
 [6 1 4]]


array([[-2.66666667,  2.33333333, -1.66666667],
       [ 5.33333333, -3.66666667,  2.33333333],
       [ 2.33333333, -4.66666667,  0.33333333]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [79]:
#Code here
a = np.random.randint(low= 1, high = 10, size=(3, 3))
print(a)
a[:, [0, 1]] = a[:,[1, 0]]
a

[[7 1 6]
 [2 9 1]
 [2 3 1]]


array([[1, 7, 6],
       [9, 2, 1],
       [3, 2, 1]])

###`Q-16:` Replace odd elements in arrays with -1.

In [83]:
#Code here
a = np.arange(10)
print(a)
a[a %2 != 0] = -1
a

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [3]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
result = np.where(a>b, a, b)
result


array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [4]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[1206, 5506, 7557, 7236, 2466],
       [2821, 4388, 8431, 4838, 1311],
       [8839, 7414, 9022, 4015, 1113],
       [2751, 1963, 1280, 2277, 4303],
       [3972, 3411, 4867, 8805, 9337],
       [ 511, 1048,  784, 8454, 9464],
       [8535, 3253, 9824, 3514, 1286],
       [4937,  235, 2245, 2521, 2791]])

In [10]:
#Code here
arr1[:, ::2]

235
9824


In [19]:
normal_array = arr1 - np.min(arr1)
normal_array = normal_array / (np.max(arr1) - np.min(arr1))
normal_array

array([[0.10126186, 0.54969236, 0.76358327, 0.73010741, 0.23266243],
       [0.26968401, 0.43310043, 0.85472938, 0.4800292 , 0.11221191],
       [0.89727813, 0.74867035, 0.9163625 , 0.39420169, 0.09156325],
       [0.26238398, 0.18020649, 0.10897904, 0.21295234, 0.4242361 ],
       [0.38971738, 0.33121285, 0.4830535 , 0.8937324 , 0.94921264],
       [0.02878298, 0.08478465, 0.0572531 , 0.85712796, 0.96245698],
       [0.86557514, 0.31473563, 1.        , 0.34195432, 0.10960476],
       [0.49035353, 0.        , 0.20961518, 0.23839816, 0.26655543]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [29]:
#Code here
def nlargest(arr, n):
  if not isinstance(arr, np.ndarray):
    raise TypeError("Input must be numpy arra only")
  if(n > len(arr)):
    return 'integer should not cross the length of the array'
  b = np.sort(arr)[::-1]
  return b[n-1]

arr = np.array([12, 34, 40, 7, 1, 0])
n = 3
print(nlargest(arr, n))

12


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [40]:
#code here
a = np.array([1,2,3])
b = np.tile(a[0], 3)
np.append(np.append(np.append(b, np.tile(a[1], 3)), np.tile(a[2], 3)), np.tile(a, 3))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])